import { Link } from 'react-router-dom'

const values = [
  { number: '01', title: 'Tận tâm với gia đình', description: 'Mỗi không gian sống đều có câu chuyện riêng và xứng đáng được chăm sóc chu đáo.' },
  { number: '02', title: 'Minh bạch trong trải nghiệm', description: 'Thông tin dịch vụ, quy trình và vai trò của từng bên luôn được trình bày rõ ràng.' },
  { number: '03', title: 'Công nghệ vì con người', description: 'Công nghệ giúp việc lựa chọn và điều phối dễ dàng hơn, không thay thế sự chủ động của con người.' },
  { number: '04', title: 'Cùng nhau tiến bộ', description: 'Phản hồi từ Customer và Staff là nền tảng để dịch vụ được cải thiện mỗi ngày.' },
]

const roles = [
  { label: 'Customer', description: 'Chủ động chọn dịch vụ, thời gian và trải nghiệm phù hợp.' },
  { label: 'Staff', description: 'Đội ngũ được tuyển chọn, đào tạo và kết nối với nhu cầu phù hợp.' },
  { label: 'Admin', description: 'Quản lý vận hành, chất lượng, tài chính và các quy trình của nền tảng.' },
]

export default function About() {
  return (
    <div className="overflow-hidden bg-white">
      <section className="relative bg-slate-950 px-5 py-20 text-white sm:py-28 lg:px-8"><div className="absolute right-0 top-0 h-full w-1/2 bg-emerald-600/10 [clip-path:polygon(35%_0,100%_0,100%_100%,0_100%)]" /><div className="relative mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[0.18em] text-emerald-300">Về CleanMaster</p><h1 className="mt-5 max-w-4xl text-4xl font-black leading-tight tracking-tight sm:text-6xl">Để việc nhà không còn là một nỗi lo thường trực.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">CleanMaster được xây dựng để kết nối nhu cầu chăm sóc tổ ấm với con người, quy trình và công nghệ phù hợp.</p></div></section>

      <section className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:py-24 lg:grid-cols-[0.8fr_1.2fr] lg:items-center lg:px-8"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-emerald-700">Câu chuyện thương hiệu</p><h2 className="mt-4 text-3xl font-black tracking-tight text-slate-900 sm:text-4xl">Một ngôi nhà sạch mở ra nhiều thời gian hơn cho điều quan trọng.</h2></div><div className="space-y-5 text-base leading-8 text-slate-600"><p>Nhịp sống hiện đại khiến việc giữ nhà cửa gọn gàng trở thành một bài toán khó: thiếu thời gian, khó tìm người phù hợp và không phải lúc nào cũng biết bắt đầu từ đâu.</p><p>CleanMaster ra đời từ mong muốn giải quyết nỗi lo đó bằng một trải nghiệm đơn giản, đáng tin cậy và có trách nhiệm. Chúng tôi kết nối Customer với Staff được tuyển chọn, để mỗi lần sử dụng dịch vụ đều bắt đầu bằng sự an tâm.</p><p>Đằng sau giao diện dễ dùng là một hệ thống hỗ trợ điều phối giúp các bên phối hợp hiệu quả hơn, nhưng quyết định cuối cùng vẫn luôn thuộc về con người.</p></div></section>

      <section className="bg-[#f3faf7] px-5 py-20 sm:py-24 lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-6 lg:grid-cols-2"><article className="rounded-3xl bg-white p-8 shadow-sm ring-1 ring-emerald-900/5 sm:p-10"><span className="text-sm font-black uppercase tracking-[0.16em] text-emerald-700">Tầm nhìn</span><h2 className="mt-5 text-3xl font-black tracking-tight text-slate-900">Trở thành nền tảng chăm sóc nhà được tin chọn.</h2><p className="mt-5 leading-7 text-slate-600">CleanMaster hướng tới một hệ sinh thái nơi Customer dễ dàng tìm được dịch vụ phù hợp, Staff có cơ hội phát triển bền vững và Admin vận hành bằng dữ liệu minh bạch.</p></article><article className="rounded-3xl bg-emerald-600 p-8 text-white shadow-sm sm:p-10"><span className="text-sm font-black uppercase tracking-[0.16em] text-emerald-100">Sứ mệnh</span><h2 className="mt-5 text-3xl font-black tracking-tight">Biến chăm sóc tổ ấm thành trải nghiệm nhẹ nhàng hơn.</h2><p className="mt-5 leading-7 text-emerald-50">Chúng tôi kết hợp dịch vụ được chuẩn hóa, đội ngũ tận tâm và công nghệ hỗ trợ để tạo ra giá trị thiết thực trong đời sống hàng ngày.</p></article></div></div></section>

      <section className="mx-auto max-w-7xl px-5 py-20 sm:py-24 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.18em] text-emerald-700">Giá trị cốt lõi</p><h2 className="mt-4 text-3xl font-black tracking-tight text-slate-900 sm:text-4xl">Điều chúng tôi giữ vững trong mỗi quyết định.</h2></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{values.map((value) => <article key={value.number} className="border-t-2 border-emerald-500 pt-5"><span className="text-sm font-black text-emerald-700">{value.number}</span><h3 className="mt-5 text-xl font-black text-slate-900">{value.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{value.description}</p></article>)}</div></section>

      <section className="bg-slate-950 px-5 py-20 text-white sm:py-24 lg:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-start"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-emerald-300">Công nghệ khác biệt</p><h2 className="mt-4 text-3xl font-black tracking-tight sm:text-4xl">AI hỗ trợ điều phối thông minh, con người giữ quyền quyết định.</h2><p className="mt-5 leading-7 text-slate-400">Đây là lớp công nghệ giúp CleanMaster hiểu nhu cầu tốt hơn và hỗ trợ vận hành hiệu quả hơn.</p></div><div className="grid gap-4 sm:grid-cols-2"><article className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><span className="text-2xl text-emerald-300">01</span><h3 className="mt-5 font-bold">Tư vấn dịch vụ</h3><p className="mt-2 text-sm leading-6 text-slate-400">AI gợi ý loại dịch vụ dựa trên nhu cầu Customer cung cấp.</p></article><article className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><span className="text-2xl text-emerald-300">02</span><h3 className="mt-5 font-bold">Hỗ trợ kết nối Staff</h3><p className="mt-2 text-sm leading-6 text-slate-400">Hệ thống hỗ trợ đối chiếu nhu cầu, thời gian và khu vực để đề xuất lựa chọn phù hợp.</p></article><article className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><span className="text-2xl text-emerald-300">03</span><h3 className="mt-5 font-bold">Hỗ trợ vận hành</h3><p className="mt-2 text-sm leading-6 text-slate-400">Dữ liệu giúp Admin theo dõi chất lượng và phát hiện điểm cần cải thiện.</p></article><article className="rounded-2xl border border-emerald-700 bg-emerald-950/50 p-6"><span className="text-2xl text-emerald-300">04</span><h3 className="mt-5 font-bold text-emerald-100">Giới hạn rõ ràng</h3><p className="mt-2 text-sm leading-6 text-emerald-200/70">AI không tự quyết định giá, thanh toán, refund, booking, đình chỉ Staff hoặc phân phối tiền.</p></article></div></div><div className="mt-12 grid gap-3 border-t border-slate-800 pt-8 sm:grid-cols-3">{roles.map((role) => <div key={role.label}><p className="font-black text-emerald-300">{role.label}</p><p className="mt-2 text-sm leading-6 text-slate-400">{role.description}</p></div>)}</div></div></section>

      <section className="px-5 py-20 sm:py-24 lg:px-8"><div className="mx-auto max-w-4xl rounded-[2rem] bg-emerald-600 px-6 py-12 text-center text-white shadow-2xl shadow-emerald-900/15 sm:px-12"><p className="text-sm font-bold uppercase tracking-[0.18em] text-emerald-100">Bắt đầu nhẹ nhàng hơn</p><h2 className="mt-4 text-3xl font-black tracking-tight sm:text-4xl">Tải CleanMaster và chăm sóc tổ ấm theo cách của bạn.</h2><p className="mx-auto mt-4 max-w-xl leading-7 text-emerald-50">Khám phá dịch vụ, chọn lịch thuận tiện và kết nối với Staff trên Mobile App.</p><Link to="/download" className="mt-8 inline-flex rounded-full bg-white px-7 py-3.5 font-bold text-emerald-700 transition hover:bg-emerald-50">Tải ứng dụng →</Link></div></section>
    </div>
  )
}
