import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { servicePackages } from '../../data/services'

function AppDownloadModal({ onClose }: { onClose: () => void }) {
  useEffect(() => {
    function handleEscape(event: KeyboardEvent) {
      if (event.key === 'Escape') onClose()
    }

    document.addEventListener('keydown', handleEscape)
    return () => document.removeEventListener('keydown', handleEscape)
  }, [onClose])

  return <div className="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/60 px-5 py-8 backdrop-blur-sm" role="presentation" onMouseDown={onClose}><div role="dialog" aria-modal="true" aria-labelledby="detail-app-title" className="w-full max-w-md rounded-3xl bg-white p-7 shadow-2xl sm:p-9" onMouseDown={(event) => event.stopPropagation()}><div className="flex items-start justify-between gap-5"><div><span className="inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-100 text-xl font-black text-emerald-700">C</span><h2 id="detail-app-title" className="mt-5 text-2xl font-black tracking-tight text-slate-900">Trải nghiệm dịch vụ trên Mobile App</h2></div><button type="button" onClick={onClose} aria-label="Đóng thông báo" className="flex h-9 w-9 items-center justify-center rounded-full text-2xl leading-none text-slate-400 hover:bg-slate-100 hover:text-slate-700 focus:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500">×</button></div><p className="mt-4 leading-7 text-slate-600">Tải ứng dụng CleanMaster để nhập chi tiết nhu cầu, chọn thời gian và xác nhận dịch vụ. Website không thực hiện booking trực tiếp.</p><div className="mt-6 grid grid-cols-2 gap-3"><Link to="/download" onClick={onClose} className="rounded-xl bg-slate-950 px-4 py-3 text-center text-sm font-bold text-white hover:bg-slate-800">App Store</Link><Link to="/download" onClick={onClose} className="rounded-xl bg-emerald-600 px-4 py-3 text-center text-sm font-bold text-white hover:bg-emerald-700">Google Play</Link></div></div></div>
}

export default function ServiceDetail() {
  const { slug } = useParams<{ slug: string }>()
  const service = servicePackages.find((item) => item.slug === slug)
  const [isModalOpen, setIsModalOpen] = useState(false)

  if (!service) {
    return <div className="mx-auto max-w-3xl px-5 py-24 text-center"><p className="text-sm font-bold uppercase tracking-[0.18em] text-emerald-700">Không tìm thấy dịch vụ</p><h1 className="mt-4 text-4xl font-black text-slate-900">Dịch vụ này chưa sẵn sàng.</h1><Link to="/services" className="mt-8 inline-flex rounded-full bg-emerald-600 px-6 py-3 font-bold text-white hover:bg-emerald-700">Xem tất cả dịch vụ</Link></div>
  }

  return <div className="overflow-hidden bg-white">
    <section className="relative isolate min-h-[520px] bg-slate-950 px-5 py-20 text-white sm:min-h-[600px] sm:py-28 lg:px-8"><img src={service.bannerImage} alt="" className="absolute inset-0 -z-20 h-full w-full object-cover opacity-45" /><div className="absolute inset-0 -z-10 bg-gradient-to-r from-slate-950 via-slate-950/75 to-slate-950/20" /><div className="mx-auto flex max-w-7xl items-center"><div className="max-w-2xl"><Link to="/services" className="text-sm font-bold text-emerald-300 hover:text-white">← Tất cả dịch vụ</Link><p className="mt-8 text-sm font-bold uppercase tracking-[0.18em] text-emerald-300">Dịch vụ CleanMaster</p><h1 className="mt-4 text-4xl font-black leading-tight tracking-tight sm:text-6xl">{service.name}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-200">{service.description} {service.suitableFor}.</p><button type="button" onClick={() => setIsModalOpen(true)} className="mt-8 rounded-full bg-emerald-500 px-6 py-3.5 font-bold text-white shadow-lg shadow-emerald-950/20 transition hover:bg-emerald-400 focus:outline-none focus-visible:ring-2 focus-visible:ring-emerald-300 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-950">Trải nghiệm dịch vụ ngay →</button></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-20 sm:py-24 lg:px-8"><div className="mx-auto max-w-2xl text-center"><p className="text-sm font-bold uppercase tracking-[0.18em] text-emerald-700">Giá trị khác biệt</p><h2 className="mt-3 text-3xl font-black tracking-tight text-slate-900 sm:text-4xl">Vì sao nên chọn CleanMaster?</h2></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{service.benefits.map((benefit) => <article key={benefit.title} className="rounded-2xl border border-slate-200 p-6 transition hover:-translate-y-1 hover:border-emerald-200 hover:shadow-lg hover:shadow-emerald-900/5"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-emerald-100 text-lg font-black text-emerald-700">{benefit.icon}</span><h3 className="mt-5 font-black text-slate-900">{benefit.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{benefit.description}</p></article>)}</div></section>

    <section className="bg-slate-50 px-5 py-20 sm:py-24 lg:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.18em] text-emerald-700">Phạm vi công việc</p><h2 className="mt-3 text-3xl font-black tracking-tight text-slate-900 sm:text-4xl">Staff sẽ làm những gì?</h2><p className="mt-4 leading-7 text-slate-600">Các đầu việc được sắp xếp theo khu vực để Customer dễ hình dung phạm vi hỗ trợ.</p></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{service.scopeOfWork.map((area) => <article key={area.area} className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200/70"><h3 className="text-xl font-black text-slate-900">{area.area}</h3><ul className="mt-5 space-y-3">{area.tasks.map((task) => <li key={task} className="flex gap-2 text-sm leading-6 text-slate-600"><span className="text-emerald-600">✓</span>{task}</li>)}</ul></article>)}</div><Link to="/services/add-ons" className="mt-8 inline-flex font-bold text-emerald-700 hover:text-emerald-800">Khám phá dịch vụ bổ sung: Sofa, Rèm, Nệm, Thảm →</Link></div></section>

    <section className="mx-auto max-w-7xl px-5 py-20 sm:py-24 lg:px-8"><div className="mx-auto max-w-2xl text-center"><p className="text-sm font-bold uppercase tracking-[0.18em] text-emerald-700">Giá tham khảo</p><h2 className="mt-3 text-3xl font-black tracking-tight text-slate-900 sm:text-4xl">Chọn thời lượng phù hợp</h2></div><div className="mx-auto mt-12 grid max-w-5xl gap-5 lg:grid-cols-3">{service.pricing.map((price) => <article key={price.label} className={`relative rounded-3xl p-7 ${price.featured ? 'bg-emerald-600 text-white shadow-xl shadow-emerald-900/15 ring-4 ring-emerald-100' : 'border border-slate-200 bg-white text-slate-900'}`}>{price.featured && <span className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-orange-500 px-3 py-1 text-xs font-bold text-white">Được chọn nhiều</span>}<h3 className="text-xl font-black">{price.label}</h3><p className={`mt-2 text-sm ${price.featured ? 'text-emerald-100' : 'text-slate-500'}`}>{price.area}</p><p className="mt-7 text-3xl font-black">{price.price}</p><ul className={`mt-6 space-y-3 text-sm ${price.featured ? 'text-emerald-50' : 'text-slate-600'}`}>{price.highlights.map((highlight) => <li key={highlight}>✓ {highlight}</li>)}</ul><button type="button" onClick={() => setIsModalOpen(true)} className={`mt-8 w-full rounded-full px-5 py-3 font-bold ${price.featured ? 'bg-white text-emerald-700 hover:bg-emerald-50' : 'bg-emerald-600 text-white hover:bg-emerald-700'}`}>Chọn gói này</button></article>)}</div><div className="mx-auto mt-8 max-w-5xl rounded-2xl bg-slate-50 p-6 text-sm leading-7 text-slate-600"><p className="font-bold text-slate-900">Lưu ý về giá</p><ul className="mt-2 list-inside list-disc">{service.pricingNotes.map((note) => <li key={note}>{note}</li>)}</ul></div></section>

    <section className="bg-[#f3faf7] px-5 py-20 sm:py-24 lg:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.18em] text-emerald-700">Quy trình trên ứng dụng</p><h2 className="mt-3 text-3xl font-black tracking-tight text-slate-900 sm:text-4xl">Cách đặt dịch vụ</h2></div><div className="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{service.bookingSteps.map((step, index) => <article key={step.title} className="relative"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-600 text-sm font-black text-white">0{index + 1}</span><h3 className="mt-5 font-black text-slate-900">{step.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{step.description}</p></article>)}</div></div></section>

    <section className="px-5 py-20 sm:py-24 lg:px-8"><div className="mx-auto max-w-5xl rounded-[2rem] bg-emerald-600 px-6 py-12 text-center text-white shadow-2xl shadow-emerald-900/15 sm:px-12"><h2 className="text-3xl font-black tracking-tight sm:text-4xl">Sẵn sàng để nhà sạch hơn?</h2><p className="mx-auto mt-4 max-w-xl leading-7 text-emerald-50">Tải ứng dụng CleanMaster để nhập chi tiết nhu cầu và bắt đầu trải nghiệm {service.name.toLowerCase()}.</p><button type="button" onClick={() => setIsModalOpen(true)} className="mt-8 rounded-full bg-white px-7 py-3.5 font-bold text-emerald-700 hover:bg-emerald-50">Trải nghiệm ngay →</button></div></section>
    {isModalOpen && <AppDownloadModal onClose={() => setIsModalOpen(false)} />}
  </div>
}
