import { Link } from 'react-router-dom'

const benefits = [
  { icon: '↗', title: 'Thu nhập hấp dẫn', description: 'Nhận thêm cơ hội việc làm phù hợp và chủ động phát triển thu nhập theo năng lực.' },
  { icon: '◷', title: 'Thời gian linh hoạt', description: 'Chủ động sắp xếp lịch nhận việc theo thời gian và khu vực thuận tiện.' },
  { icon: '✦', title: 'Được đào tạo bài bản', description: 'Được hướng dẫn quy trình, kỹ năng và tiêu chuẩn phục vụ trước khi bắt đầu.' },
]

const requirements = ['CCCD hoặc giấy tờ tùy thân hợp lệ', 'Sơ yếu lý lịch có thông tin rõ ràng', 'Giấy khám sức khỏe theo yêu cầu tuyển chọn']

const steps = [
  { number: '01', title: 'Tải ứng dụng Staff', description: 'Tìm hiểu cơ hội hợp tác và bắt đầu gửi thông tin trên kênh tuyển dụng.' },
  { number: '02', title: 'Đăng ký hồ sơ', description: 'Cung cấp thông tin cá nhân và hồ sơ cần thiết để công ty tiếp nhận.' },
  { number: '03', title: 'Phỏng vấn & đào tạo', description: 'Tham gia phỏng vấn, xác minh hồ sơ và chương trình đào tạo phù hợp.' },
  { number: '04', title: 'Bắt đầu nhận việc', description: 'Sau khi được tuyển chọn, Admin tạo tài khoản Staff để bạn bắt đầu.' },
]

export default function Cooperation() {
  return (
    <div className="overflow-hidden bg-white">
      <section className="bg-[#fff7ed] px-5 py-20 sm:py-28 lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-orange-700">Cơ hội trở thành Staff</p><h1 className="mt-5 text-4xl font-black leading-tight tracking-tight text-slate-950 sm:text-6xl">Làm việc linh hoạt, tạo giá trị mỗi ngày.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Gia nhập đội ngũ CleanMaster để kết nối với những cơ hội phù hợp, được đào tạo bài bản và đồng hành trong một nền tảng chuyên nghiệp.</p><Link to="/download" className="mt-8 inline-flex items-center gap-2 rounded-full bg-orange-600 px-6 py-3.5 font-bold text-white shadow-lg shadow-orange-600/20 transition hover:bg-orange-700 focus:outline-none focus-visible:ring-2 focus-visible:ring-orange-500 focus-visible:ring-offset-2">Tải ứng dụng Staff <span aria-hidden="true">→</span></Link><p className="mt-4 text-sm text-slate-500">Tài khoản Staff được Admin tạo sau khi bạn hoàn tất tuyển chọn.</p></div><div className="relative"><div className="overflow-hidden rounded-[2rem] rounded-br-[5rem] border-8 border-white shadow-2xl shadow-orange-950/10"><img src="https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1100&q=85" alt="Nhân viên đang chuẩn bị dụng cụ dọn dẹp" className="aspect-[4/3] w-full object-cover" /></div><div className="absolute -bottom-5 -left-3 rounded-2xl bg-slate-950 px-5 py-4 text-white shadow-xl sm:-left-7"><p className="text-xs text-slate-400">Cùng CleanMaster</p><p className="mt-1 font-bold">Tạo nên không gian tốt hơn</p></div></div></div></section>

      <section className="mx-auto max-w-7xl px-5 py-20 sm:py-24 lg:px-8"><div className="mx-auto max-w-2xl text-center"><p className="text-sm font-bold uppercase tracking-[0.18em] text-orange-700">Quyền lợi đồng hành</p><h2 className="mt-3 text-3xl font-black tracking-tight text-slate-900 sm:text-4xl">Một nền tảng để bạn phát triển bền vững</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{benefits.map((benefit) => <article key={benefit.title} className="rounded-3xl border border-slate-200 bg-white p-7 transition hover:-translate-y-1 hover:border-orange-200 hover:shadow-lg hover:shadow-orange-900/5"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-orange-100 text-xl font-black text-orange-700">{benefit.icon}</span><h3 className="mt-6 text-xl font-black text-slate-900">{benefit.title}</h3><p className="mt-3 leading-7 text-slate-600">{benefit.description}</p></article>)}</div></section>

      <section className="bg-slate-50 px-5 py-20 sm:py-24 lg:px-8"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1fr_0.9fr] lg:items-start"><div><p className="text-sm font-bold uppercase tracking-[0.18em] text-orange-700">Hồ sơ cần chuẩn bị</p><h2 className="mt-3 text-3xl font-black tracking-tight text-slate-900 sm:text-4xl">Bắt đầu từ những thông tin rõ ràng</h2><p className="mt-5 max-w-xl leading-7 text-slate-600">Chuẩn bị trước các giấy tờ cơ bản để quy trình tiếp nhận hồ sơ diễn ra thuận lợi hơn.</p><ul className="mt-8 space-y-4">{requirements.map((requirement) => <li key={requirement} className="flex items-start gap-3"><span className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-orange-100 text-sm font-black text-orange-700">✓</span><span className="font-semibold text-slate-800">{requirement}</span></li>)}</ul></div><div className="rounded-3xl bg-white p-7 shadow-sm ring-1 ring-slate-200 sm:p-9"><p className="text-sm font-bold text-orange-700">Lưu ý quan trọng</p><h3 className="mt-3 text-2xl font-black text-slate-900">Website chỉ tiếp nhận thông tin tuyển dụng</h3><p className="mt-4 leading-7 text-slate-600">Bạn không tự đăng ký tài khoản Staff trên Mobile App. Sau khi công ty phỏng vấn, đào tạo và tuyển chọn, Admin sẽ tạo tài khoản để bạn bắt đầu nhận việc.</p></div></div></section>

      <section className="mx-auto max-w-7xl px-5 py-20 sm:py-24 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.18em] text-orange-700">Quy trình 4 bước</p><h2 className="mt-3 text-3xl font-black tracking-tight text-slate-900 sm:text-4xl">Từ hồ sơ đến cơ hội nhận việc</h2></div><div className="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{steps.map((step) => <article key={step.number} className="relative border-t-2 border-orange-500 pt-5"><span className="text-sm font-black text-orange-700">{step.number}</span><h3 className="mt-5 text-xl font-black text-slate-900">{step.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{step.description}</p></article>)}</div></section>

      <section className="px-5 pb-20 sm:pb-24 lg:px-8"><div className="mx-auto max-w-4xl rounded-[2rem] bg-orange-600 px-6 py-12 text-center text-white shadow-2xl shadow-orange-900/15 sm:px-12"><p className="text-sm font-bold uppercase tracking-[0.18em] text-orange-100">Sẵn sàng đồng hành?</p><h2 className="mt-4 text-3xl font-black tracking-tight sm:text-4xl">Bắt đầu hành trình Staff cùng CleanMaster.</h2><Link to="/download" className="mt-8 inline-flex rounded-full bg-white px-7 py-3.5 font-bold text-orange-700 transition hover:bg-orange-50">Tải ứng dụng Staff →</Link></div></section>
    </div>
  )
}
